// Parses the prep-plan markdown files in the repo root into seed data
// (phases -> sprints/weeks -> tickets) consumed by the app on first login.
//
// Run:  node scripts/generate-seed.mjs
// Output: app/src/data/seed.ts

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const OUT = join(ROOT, 'app', 'src', 'data', 'seed.ts');

const PHASES = [
  { key: 'phase-1', name: 'Phase 1 — Rebuild Foundations', short: 'Foundations',
    goal: 'DSA patterns back to easy–medium fluency, core JS solid, machine-coding muscle started.',
    weeks: [1, 2, 3, 4] },
  { key: 'phase-2', name: 'Phase 2 — Build Interview Skills', short: 'Interview Skills',
    goal: 'Medium DSA fluency, deep JS, fast machine coding, and frontend system design in earnest.',
    weeks: [5, 6, 7, 8] },
  { key: 'phase-3', name: 'Phase 3 — Interview Mode', short: 'Interview Mode',
    goal: 'Mocks, polish, company-specific tailoring, full applying push, iterate on real feedback.',
    weeks: [9, 10, 11, 12] },
];

const DAY_ORDER = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

// Strip markdown emphasis / code ticks for clean titles.
function clean(s) {
  return s
    .replace(/\*\*/g, '')
    .replace(/`/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// Classify a task cell into a track.
function classifyTrack(text, fallback) {
  const t = text.toLowerCase();
  if (/(machine[- ]?coding|mock machine|rebuild|progress-bar|kanban|carousel|modal|toast|autocomplete|typeahead|accordion|tabs|star rating|todo|data table|infinite scroll|nested comments|tree view|otp|form validation)/.test(t))
    return 'Machine Coding';
  if (/(system design|radio|design (an?|system)|news feed|chat application|e-commerce|design system|component library|email client|google-docs)/.test(t))
    return 'System Design';
  if (/(star story|behavioral|behaviour)/.test(t)) return 'Behavioral';
  if (/^review$|review misses|light review|^review the/.test(t)) return 'Review';
  return fallback;
}

function priorityFor(track) {
  if (track === 'Machine Coding' || track === 'System Design') return 'high';
  if (track === 'Behavioral' || track === 'Review') return 'low';
  return 'medium';
}

function parseWeek(weekNum) {
  const file = join(ROOT, `week-${weekNum}-deep-dive.md`);
  if (!existsSync(file)) throw new Error(`Missing ${file}`);
  const md = readFileSync(file, 'utf8');
  const lines = md.split('\n');

  // Intro metadata
  let tracks = '';
  let goal = '';
  for (const line of lines) {
    if (line.startsWith('**Tracks this week:**')) tracks = clean(line.replace('**Tracks this week:**', ''));
    if (line.startsWith('**Goal by Sunday:**')) goal = clean(line.replace('**Goal by Sunday:**', ''));
    if (tracks && goal) break;
  }

  // Find the day-by-day table: header row contains "Day" then "| Mon |" rows.
  const headerIdx = lines.findIndex((l) => /^\|\s*Day\s*\|/.test(l));
  const header = lines[headerIdx].split('|').map((c) => clean(c)).filter(Boolean);
  const col2Label = header[1] || 'DSA';
  const col3Label = header[2] || 'JS';

  const col2Fallback = /dsa|coding/i.test(col2Label) ? 'DSA' : 'JavaScript';
  const col3Fallback = /js|javascript/i.test(col3Label) ? 'JavaScript' : 'Main';

  const tickets = [];
  for (let i = headerIdx + 2; i < lines.length; i++) {
    const line = lines[i];
    if (!line.startsWith('|')) break;
    const cells = line.split('|').slice(1, -1).map((c) => c.trim());
    const day = clean(cells[0]);
    if (!DAY_ORDER.includes(day)) continue;

    const dayCells = cells.slice(1);
    dayCells.forEach((raw, idx) => {
      const text = clean(raw);
      if (!text) return;
      const fallback = idx === 0 ? col2Fallback : col3Fallback;
      const track = classifyTrack(text, fallback);
      tickets.push({
        key: `w${weekNum}-${day.toLowerCase()}-${idx}`,
        title: text.length > 80 ? text.slice(0, 77) + '…' : text,
        description: text,
        track,
        day,
        priority: priorityFor(track),
        status: 'todo',
      });
    });
  }

  return { weekNum, tracks, goal, tickets };
}

const phases = PHASES.map((p, pi) => ({
  key: p.key,
  name: p.name,
  short: p.short,
  goal: p.goal,
  order: pi,
  sprints: p.weeks.map((w, wi) => {
    const parsed = parseWeek(w);
    return {
      key: `week-${w}`,
      weekNumber: w,
      title: `Week ${w}`,
      goal: parsed.goal,
      tracks: parsed.tracks,
      order: wi,
      tickets: parsed.tickets.map((t, ti) => ({ ...t, order: ti })),
    };
  }),
}));

const totalTickets = phases.reduce(
  (a, p) => a + p.sprints.reduce((b, s) => b + s.tickets.length, 0),
  0,
);

const banner = `// AUTO-GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Source: the week-*-deep-dive.md prep-plan files in the repo root.
// Phases: ${phases.length} · Sprints: ${phases.reduce((a, p) => a + p.sprints.length, 0)} · Tickets: ${totalTickets}
`;

const body = `${banner}
import type { SeedPhase } from '../lib/types';

export const SEED_PHASES: SeedPhase[] = ${JSON.stringify(phases, null, 2)};

export const SEED_VERSION = 1;
`;

writeFileSync(OUT, body);
console.log(`Wrote ${OUT}`);
console.log(`Phases: ${phases.length}, Sprints: ${phases.reduce((a, p) => a + p.sprints.length, 0)}, Tickets: ${totalTickets}`);
