// AUTO-GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Source: the week-*-deep-dive.md prep-plan files in the repo root.
// Phases: 3 · Sprints: 12 · Tickets: 146

import type { SeedPhase } from '../lib/types';

export const SEED_PHASES: SeedPhase[] = [
  {
    "key": "phase-1",
    "name": "Phase 1 — Rebuild Foundations",
    "short": "Foundations",
    "goal": "DSA patterns back to easy–medium fluency, core JS solid, machine-coding muscle started.",
    "order": 0,
    "sprints": [
      {
        "key": "week-1",
        "weekNumber": 1,
        "title": "Week 1",
        "goal": "you can explain closures cold and write debounce/throttle from memory; you can build a small interactive component in vanilla JS without panicking; and the two-pointer + hashing patterns feel automatic.",
        "tracks": "DSA (arrays/strings, two pointers, hashing) · JavaScript (execution context, scope, hoisting, closures + debounce/throttle) · Machine coding (Star Rating, Todo) · System design (not yet — light Sunday).",
        "order": 0,
        "tickets": [
          {
            "key": "w1-mon-0",
            "title": "Two Sum, Contains Duplicate",
            "description": "Two Sum, Contains Duplicate",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w1-mon-1",
            "title": "Execution context, scope, hoisting",
            "description": "Execution context, scope, hoisting",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w1-tue-0",
            "title": "Valid Anagram, Group Anagrams",
            "description": "Valid Anagram, Group Anagrams",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w1-tue-1",
            "title": "Closures (deep) — read + examples",
            "description": "Closures (deep) — read + examples",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w1-wed-0",
            "title": "Reverse String, Valid Palindrome",
            "description": "Reverse String, Valid Palindrome",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w1-wed-1",
            "title": "Implement debounce (both variants)",
            "description": "Implement debounce (both variants)",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w1-thu-0",
            "title": "Two Sum II (sorted), 3Sum (intro)",
            "description": "Two Sum II (sorted), 3Sum (intro)",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w1-thu-1",
            "title": "Implement throttle + closure interview patterns",
            "description": "Implement throttle + closure interview patterns",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w1-fri-0",
            "title": "Best Time to Buy & Sell Stock + redo any shaky one",
            "description": "Best Time to Buy & Sell Stock + redo any shaky one",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w1-fri-1",
            "title": "Predict-the-output drills + memory leaks",
            "description": "Predict-the-output drills + memory leaks",
            "track": "JavaScript",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w1-sat-0",
            "title": "Machine coding: Star Rating → Todo",
            "description": "Machine coding: Star Rating → Todo",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w1-sun-0",
            "title": "Review week + 2nd pass on weak spots + skim \"what is FE system design\" + draf…",
            "description": "Review week + 2nd pass on weak spots + skim \"what is FE system design\" + draft 1 STAR story",
            "track": "System Design",
            "day": "Sun",
            "priority": "high",
            "status": "todo",
            "order": 11
          }
        ]
      },
      {
        "key": "week-2",
        "weekNumber": 2,
        "title": "Week 2",
        "goal": "you can explain the 4 rules of this and why arrow functions differ; you can write myCall/myApply/myBind; and the sliding-window pattern (fixed + variable) is automatic.",
        "tracks": "",
        "order": 1,
        "tickets": [
          {
            "key": "w2-mon-0",
            "title": "Maximum Average Subarray I (fixed window)",
            "description": "Maximum Average Subarray I (fixed window)",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w2-mon-1",
            "title": "The 4 rules of this",
            "description": "The 4 rules of this",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w2-tue-0",
            "title": "Longest Substring Without Repeating Chars",
            "description": "Longest Substring Without Repeating Chars",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w2-tue-1",
            "title": "Arrow vs regular functions; losing this in callbacks",
            "description": "Arrow vs regular functions; losing this in callbacks",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w2-wed-0",
            "title": "Minimum Size Subarray Sum",
            "description": "Minimum Size Subarray Sum",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w2-wed-1",
            "title": "call / apply / bind — usage → implement myCall",
            "description": "call / apply / bind — usage → implement myCall",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w2-thu-0",
            "title": "Longest Repeating Character Replacement",
            "description": "Longest Repeating Character Replacement",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w2-thu-1",
            "title": "Implement myApply + myBind",
            "description": "Implement myApply + myBind",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w2-fri-0",
            "title": "Permutation in String + Subarray Sum = K (prefix sum)",
            "description": "Permutation in String + Subarray Sum = K (prefix sum)",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w2-fri-1",
            "title": "Review + predict-the-output drills on this",
            "description": "Review + predict-the-output drills on this",
            "track": "JavaScript",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w2-sat-0",
            "title": "Machine coding: Accordion → Tabs",
            "description": "Machine coding: Accordion → Tabs",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w2-sun-0",
            "title": "Review + 2nd pass on weak spots + draft 1 STAR story",
            "description": "Review + 2nd pass on weak spots + draft 1 STAR story",
            "track": "Behavioral",
            "day": "Sun",
            "priority": "low",
            "status": "todo",
            "order": 11
          }
        ]
      },
      {
        "key": "week-3",
        "weekNumber": 3,
        "title": "Week 3",
        "goal": "you can explain the prototype chain and what new actually does; you can implement new and Object.create; and you can build a debounced autocomplete with keyboard navigation.",
        "tracks": "",
        "order": 2,
        "tickets": [
          {
            "key": "w3-mon-0",
            "title": "Valid Parentheses",
            "description": "Valid Parentheses",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w3-mon-1",
            "title": "Prototypes & the prototype chain",
            "description": "Prototypes & the prototype chain",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w3-tue-0",
            "title": "Min Stack",
            "description": "Min Stack",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w3-tue-1",
            "title": "Prototypal inheritance; __proto__ vs prototype",
            "description": "Prototypal inheritance; __proto__ vs prototype",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w3-wed-0",
            "title": "Evaluate Reverse Polish Notation",
            "description": "Evaluate Reverse Polish Notation",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w3-wed-1",
            "title": "What new does → implement myNew",
            "description": "What new does → implement myNew",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w3-thu-0",
            "title": "Daily Temperatures (monotonic stack)",
            "description": "Daily Temperatures (monotonic stack)",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w3-thu-1",
            "title": "Object.create → implement it; ES6 classes as sugar",
            "description": "Object.create → implement it; ES6 classes as sugar",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w3-fri-0",
            "title": "Implement Queue using Stacks + review",
            "description": "Implement Queue using Stacks + review",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w3-fri-1",
            "title": "Review + predict-the-output on prototype lookup",
            "description": "Review + predict-the-output on prototype lookup",
            "track": "JavaScript",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w3-sat-0",
            "title": "Machine coding: Autocomplete / Typeahead",
            "description": "Machine coding: Autocomplete / Typeahead",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w3-sun-0",
            "title": "Review + 2nd pass + draft 1 STAR story",
            "description": "Review + 2nd pass + draft 1 STAR story",
            "track": "Behavioral",
            "day": "Sun",
            "priority": "low",
            "status": "todo",
            "order": 11
          }
        ]
      },
      {
        "key": "week-4",
        "weekNumber": 4,
        "title": "Week 4",
        "goal": "you can trace the exact output order of mixed sync / setTimeout / Promise code; you can write a bug-free binary search (and \"binary search on the answer\"); and you understand RADIO before system design starts next week.",
        "tracks": "",
        "order": 3,
        "tickets": [
          {
            "key": "w4-mon-0",
            "title": "Binary Search (nail the template)",
            "description": "Binary Search (nail the template)",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w4-mon-1",
            "title": "Call stack → event loop big picture",
            "description": "Call stack → event loop big picture",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w4-tue-0",
            "title": "Search in Rotated Sorted Array",
            "description": "Search in Rotated Sorted Array",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w4-tue-1",
            "title": "Macrotasks (setTimeout) vs microtasks (Promises)",
            "description": "Macrotasks (setTimeout) vs microtasks (Promises)",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w4-wed-0",
            "title": "Find First and Last Position",
            "description": "Find First and Last Position",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w4-wed-1",
            "title": "Predict-the-output drills (mixed)",
            "description": "Predict-the-output drills (mixed)",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w4-thu-0",
            "title": "Koko Eating Bananas (search on answer)",
            "description": "Koko Eating Bananas (search on answer)",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w4-thu-1",
            "title": "async/await is microtasks under the hood",
            "description": "async/await is microtasks under the hood",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w4-fri-0",
            "title": "Search a 2D Matrix + review",
            "description": "Search a 2D Matrix + review",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w4-fri-1",
            "title": "Review + more output drills",
            "description": "Review + more output drills",
            "track": "JavaScript",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w4-sat-0",
            "title": "Machine coding: Carousel / Image Slider",
            "description": "Machine coding: Carousel / Image Slider",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w4-sun-0",
            "title": "Learn RADIO framework + draft 1 STAR story",
            "description": "Learn RADIO framework + draft 1 STAR story",
            "track": "System Design",
            "day": "Sun",
            "priority": "high",
            "status": "todo",
            "order": 11
          }
        ]
      }
    ]
  },
  {
    "key": "phase-2",
    "name": "Phase 2 — Build Interview Skills",
    "short": "Interview Skills",
    "goal": "Medium DSA fluency, deep JS, fast machine coding, and frontend system design in earnest.",
    "order": 1,
    "sprints": [
      {
        "key": "week-5",
        "weekNumber": 5,
        "title": "Week 5",
        "goal": "you can implement Promise.all/race/allSettled; you can reverse a linked list and use fast/slow pointers; and you can walk through designing an autocomplete component using RADIO end-to-end.",
        "tracks": "",
        "order": 0,
        "tickets": [
          {
            "key": "w5-mon-0",
            "title": "Reverse Linked List",
            "description": "Reverse Linked List",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w5-mon-1",
            "title": "Promises deeply (states, chaining)",
            "description": "Promises deeply (states, chaining)",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w5-tue-0",
            "title": "Linked List Cycle (fast/slow)",
            "description": "Linked List Cycle (fast/slow)",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w5-tue-1",
            "title": "async/await, error handling",
            "description": "async/await, error handling",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w5-wed-0",
            "title": "Middle of the Linked List",
            "description": "Middle of the Linked List",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w5-wed-1",
            "title": "Implement Promise.all",
            "description": "Implement Promise.all",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w5-thu-0",
            "title": "Merge Two Sorted Lists",
            "description": "Merge Two Sorted Lists",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w5-thu-1",
            "title": "Implement Promise.race + allSettled",
            "description": "Implement Promise.race + allSettled",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w5-fri-0",
            "title": "Remove Nth Node From End + review",
            "description": "Remove Nth Node From End + review",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w5-fri-1",
            "title": "Review",
            "description": "Review",
            "track": "Review",
            "day": "Fri",
            "priority": "low",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w5-sat-0",
            "title": "Machine coding: Modal → Toast queue",
            "description": "Machine coding: Modal → Toast queue",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w5-sun-0",
            "title": "System design: Autocomplete (RADIO) + draft 1 STAR story",
            "description": "System design: Autocomplete (RADIO) + draft 1 STAR story",
            "track": "Machine Coding",
            "day": "Sun",
            "priority": "high",
            "status": "todo",
            "order": 11
          }
        ]
      },
      {
        "key": "week-6",
        "weekNumber": 6,
        "title": "Week 6",
        "goal": "you can implement map/filter/reduce and curry; you can solve subsets/permutations with backtracking; and you can design a carousel component, reasoning about lazy-loading and accessibility.",
        "tracks": "",
        "order": 1,
        "tickets": [
          {
            "key": "w6-mon-0",
            "title": "Subsets",
            "description": "Subsets",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w6-mon-1",
            "title": "Implement map + filter",
            "description": "Implement map + filter",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w6-tue-0",
            "title": "Permutations",
            "description": "Permutations",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w6-tue-1",
            "title": "Implement reduce",
            "description": "Implement reduce",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w6-wed-0",
            "title": "Combination Sum",
            "description": "Combination Sum",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w6-wed-1",
            "title": "forEach + flat; currying concept",
            "description": "forEach + flat; currying concept",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w6-thu-0",
            "title": "Generate Parentheses",
            "description": "Generate Parentheses",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w6-thu-1",
            "title": "Implement curry",
            "description": "Implement curry",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w6-fri-0",
            "title": "Word Search + review",
            "description": "Word Search + review",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w6-fri-1",
            "title": "Review",
            "description": "Review",
            "track": "Review",
            "day": "Fri",
            "priority": "low",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w6-sat-0",
            "title": "Machine coding: Nested Comments / Tree view",
            "description": "Machine coding: Nested Comments / Tree view",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w6-sun-0",
            "title": "System design: Image Carousel (RADIO) + draft 1 STAR story",
            "description": "System design: Image Carousel (RADIO) + draft 1 STAR story",
            "track": "Machine Coding",
            "day": "Sun",
            "priority": "high",
            "status": "todo",
            "order": 11
          }
        ]
      },
      {
        "key": "week-7",
        "weekNumber": 7,
        "title": "Week 7",
        "goal": "you can explain bubbling/capturing and event delegation and build an Event Emitter; you can do BFS/DFS on trees; and you can design a news feed, reasoning about pagination, optimistic updates, and virtualization.",
        "tracks": "",
        "order": 2,
        "tickets": [
          {
            "key": "w7-mon-0",
            "title": "Maximum Depth of Binary Tree",
            "description": "Maximum Depth of Binary Tree",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w7-mon-1",
            "title": "Event bubbling vs capturing",
            "description": "Event bubbling vs capturing",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w7-tue-0",
            "title": "Binary Tree Level Order Traversal (BFS)",
            "description": "Binary Tree Level Order Traversal (BFS)",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w7-tue-1",
            "title": "Event delegation (and why it scales)",
            "description": "Event delegation (and why it scales)",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w7-wed-0",
            "title": "Validate Binary Search Tree",
            "description": "Validate Binary Search Tree",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w7-wed-1",
            "title": "Implement an Event Emitter",
            "description": "Implement an Event Emitter",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w7-thu-0",
            "title": "Invert Binary Tree",
            "description": "Invert Binary Tree",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w7-thu-1",
            "title": "DOM traversal/manipulation in vanilla JS",
            "description": "DOM traversal/manipulation in vanilla JS",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w7-fri-0",
            "title": "Lowest Common Ancestor of a BST + review",
            "description": "Lowest Common Ancestor of a BST + review",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w7-fri-1",
            "title": "Review",
            "description": "Review",
            "track": "Review",
            "day": "Fri",
            "priority": "low",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w7-sat-0",
            "title": "Machine coding: Data Table (sort + filter + pagination)",
            "description": "Machine coding: Data Table (sort + filter + pagination)",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w7-sun-0",
            "title": "System design: News Feed (RADIO) + draft 1 STAR story",
            "description": "System design: News Feed (RADIO) + draft 1 STAR story",
            "track": "System Design",
            "day": "Sun",
            "priority": "high",
            "status": "todo",
            "order": 11
          }
        ]
      },
      {
        "key": "week-8",
        "weekNumber": 8,
        "title": "Week 8",
        "goal": "you can explain memory leaks and write memoize; you can do graph BFS/DFS; and you can design an e-commerce site, leading with the SEO/SSR decision that defines it. This completes Phase 2.",
        "tracks": "",
        "order": 3,
        "tickets": [
          {
            "key": "w8-mon-0",
            "title": "Number of Islands (DFS)",
            "description": "Number of Islands (DFS)",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w8-mon-1",
            "title": "Memory leaks (the 4 common causes)",
            "description": "Memory leaks (the 4 common causes)",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w8-tue-0",
            "title": "Rotting Oranges (BFS)",
            "description": "Rotting Oranges (BFS)",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w8-tue-1",
            "title": "Garbage collection model",
            "description": "Garbage collection model",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w8-wed-0",
            "title": "Clone Graph",
            "description": "Clone Graph",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w8-wed-1",
            "title": "Memoization → implement memoize",
            "description": "Memoization → implement memoize",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w8-thu-0",
            "title": "Course Schedule (topological / cycle)",
            "description": "Course Schedule (topological / cycle)",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w8-thu-1",
            "title": "Perf: reflow/repaint, when to debounce/throttle renders",
            "description": "Perf: reflow/repaint, when to debounce/throttle renders",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w8-fri-0",
            "title": "Pacific Atlantic Water Flow + review",
            "description": "Pacific Atlantic Water Flow + review",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w8-fri-1",
            "title": "Review",
            "description": "Review",
            "track": "Review",
            "day": "Fri",
            "priority": "low",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w8-sat-0",
            "title": "Machine coding: Infinite Scroll + Virtualized List",
            "description": "Machine coding: Infinite Scroll + Virtualized List",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w8-sun-0",
            "title": "System design: E-commerce (RADIO) + draft 1 STAR story",
            "description": "System design: E-commerce (RADIO) + draft 1 STAR story",
            "track": "System Design",
            "day": "Sun",
            "priority": "high",
            "status": "todo",
            "order": 11
          }
        ]
      }
    ]
  },
  {
    "key": "phase-3",
    "name": "Phase 3 — Interview Mode",
    "short": "Interview Mode",
    "goal": "Mocks, polish, company-specific tailoring, full applying push, iterate on real feedback.",
    "order": 2,
    "sprints": [
      {
        "key": "week-9",
        "weekNumber": 9,
        "title": "Week 9",
        "goal": "you can write the 1D DP staples; you can implement deep clone (with circular refs) and deep equal; and you can design a chat app, reasoning about WebSockets, offline queueing, and message ordering.",
        "tracks": "",
        "order": 0,
        "tickets": [
          {
            "key": "w9-mon-0",
            "title": "Climbing Stairs",
            "description": "Climbing Stairs",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w9-mon-1",
            "title": "DP intuition: memoization vs tabulation",
            "description": "DP intuition: memoization vs tabulation",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w9-tue-0",
            "title": "House Robber",
            "description": "House Robber",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w9-tue-1",
            "title": "ES modules (ESM) vs CommonJS",
            "description": "ES modules (ESM) vs CommonJS",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w9-wed-0",
            "title": "Coin Change",
            "description": "Coin Change",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w9-wed-1",
            "title": "Generators & iterables → implement deepClone",
            "description": "Generators & iterables → implement deepClone",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w9-thu-0",
            "title": "Longest Increasing Subsequence",
            "description": "Longest Increasing Subsequence",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w9-thu-1",
            "title": "Implement deepEqual",
            "description": "Implement deepEqual",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w9-fri-0",
            "title": "Review the four",
            "description": "Review the four",
            "track": "Review",
            "day": "Fri",
            "priority": "low",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w9-fri-1",
            "title": "Review",
            "description": "Review",
            "track": "Review",
            "day": "Fri",
            "priority": "low",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w9-sat-0",
            "title": "Machine coding: OTP input (or Form validation)",
            "description": "Machine coding: OTP input (or Form validation)",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w9-sun-0",
            "title": "System design: Chat application (RADIO) + draft 1 STAR story",
            "description": "System design: Chat application (RADIO) + draft 1 STAR story",
            "track": "System Design",
            "day": "Sun",
            "priority": "high",
            "status": "todo",
            "order": 11
          }
        ]
      },
      {
        "key": "week-10",
        "weekNumber": 10,
        "title": "Week 10",
        "goal": "you can handle interval problems and know how a heap works (and that JS has none built in); you can explain storage options, CORS, and the critical rendering path; and you can design a component library, reasoning about tokens, theming, a11y, and API design.",
        "tracks": "",
        "order": 1,
        "tickets": [
          {
            "key": "w10-mon-0",
            "title": "Merge Intervals",
            "description": "Merge Intervals",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w10-mon-1",
            "title": "localStorage vs sessionStorage vs cookies",
            "description": "localStorage vs sessionStorage vs cookies",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w10-tue-0",
            "title": "Insert Interval / Non-overlapping Intervals",
            "description": "Insert Interval / Non-overlapping Intervals",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w10-tue-1",
            "title": "fetch, XHR, and the request lifecycle",
            "description": "fetch, XHR, and the request lifecycle",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w10-wed-0",
            "title": "Kth Largest Element (heap)",
            "description": "Kth Largest Element (heap)",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w10-wed-1",
            "title": "CORS — what it is and why preflight",
            "description": "CORS — what it is and why preflight",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w10-thu-0",
            "title": "Top K Frequent Elements",
            "description": "Top K Frequent Elements",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w10-thu-1",
            "title": "Critical rendering path; reflow vs repaint",
            "description": "Critical rendering path; reflow vs repaint",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w10-fri-0",
            "title": "Review intervals + heap",
            "description": "Review intervals + heap",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w10-fri-1",
            "title": "Review",
            "description": "Review",
            "track": "Review",
            "day": "Fri",
            "priority": "low",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w10-sat-0",
            "title": "Machine coding: Progress-bar queue (or Kanban)",
            "description": "Machine coding: Progress-bar queue (or Kanban)",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w10-sun-0",
            "title": "System design: Design System / Component Library (RADIO) + draft 1 STAR story",
            "description": "System design: Design System / Component Library (RADIO) + draft 1 STAR story",
            "track": "System Design",
            "day": "Sun",
            "priority": "high",
            "status": "todo",
            "order": 11
          }
        ]
      },
      {
        "key": "week-11",
        "weekNumber": 11,
        "title": "Week 11",
        "goal": "you're comfortable reading and writing typed code (TS is a screening gate in 2026); you can explain Angular and React internals at a high level; and you can design a complex stateful app and speak to the cross-cutting topics interviewers probe.",
        "tracks": "",
        "order": 2,
        "tickets": [
          {
            "key": "w11-mon-0",
            "title": "Revisit weakest pattern #1 (timed)",
            "description": "Revisit weakest pattern #1 (timed)",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w11-mon-1",
            "title": "TS: types, interfaces, unions",
            "description": "TS: types, interfaces, unions",
            "track": "JavaScript",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w11-tue-0",
            "title": "Revisit weakest pattern #2 (timed)",
            "description": "Revisit weakest pattern #2 (timed)",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w11-tue-1",
            "title": "TS: generics",
            "description": "TS: generics",
            "track": "JavaScript",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w11-wed-0",
            "title": "2 mixed mediums (45-min timer, narrate)",
            "description": "2 mixed mediums (45-min timer, narrate)",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w11-wed-1",
            "title": "TS: utility types (Partial/Pick/Omit/Record)",
            "description": "TS: utility types (Partial/Pick/Omit/Record)",
            "track": "JavaScript",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w11-thu-0",
            "title": "2 mixed mediums (45-min timer)",
            "description": "2 mixed mediums (45-min timer)",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w11-thu-1",
            "title": "Angular internals: change detection + Signals",
            "description": "Angular internals: change detection + Signals",
            "track": "JavaScript",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w11-fri-0",
            "title": "Review misses",
            "description": "Review misses",
            "track": "Review",
            "day": "Fri",
            "priority": "low",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w11-fri-1",
            "title": "React internals: VDOM, reconciliation, hooks",
            "description": "React internals: VDOM, reconciliation, hooks",
            "track": "JavaScript",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w11-sat-0",
            "title": "Machine coding: rebuild 2 favorites under strict time",
            "description": "Machine coding: rebuild 2 favorites under strict time",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w11-sun-0",
            "title": "System design: Email client (RADIO) + cross-cutting concepts + draft 1 STAR s…",
            "description": "System design: Email client (RADIO) + cross-cutting concepts + draft 1 STAR story",
            "track": "System Design",
            "day": "Sun",
            "priority": "high",
            "status": "todo",
            "order": 11
          }
        ]
      },
      {
        "key": "week-12",
        "weekNumber": 12,
        "title": "Week 12",
        "goal": "you've done full timed mocks of every round type, your 6 STAR stories are polished, and you're applying aggressively with referrals in motion.",
        "tracks": "",
        "order": 3,
        "tickets": [
          {
            "key": "w12-mon-0",
            "title": "2 company-tagged problems",
            "description": "2 company-tagged problems",
            "track": "DSA",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 0
          },
          {
            "key": "w12-mon-1",
            "title": "Rapid JS revision (quick-fire all topics)",
            "description": "Rapid JS revision (quick-fire all topics)",
            "track": "Main",
            "day": "Mon",
            "priority": "medium",
            "status": "todo",
            "order": 1
          },
          {
            "key": "w12-tue-0",
            "title": "2 company-tagged problems",
            "description": "2 company-tagged problems",
            "track": "DSA",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 2
          },
          {
            "key": "w12-tue-1",
            "title": "Redo any shaky polyfills (debounce, Promise.all, deepClone)",
            "description": "Redo any shaky polyfills (debounce, Promise.all, deepClone)",
            "track": "Main",
            "day": "Tue",
            "priority": "medium",
            "status": "todo",
            "order": 3
          },
          {
            "key": "w12-wed-0",
            "title": "1 warm-up problem",
            "description": "1 warm-up problem",
            "track": "DSA",
            "day": "Wed",
            "priority": "medium",
            "status": "todo",
            "order": 4
          },
          {
            "key": "w12-wed-1",
            "title": "Mock machine-coding round (timed, out loud)",
            "description": "Mock machine-coding round (timed, out loud)",
            "track": "Machine Coding",
            "day": "Wed",
            "priority": "high",
            "status": "todo",
            "order": 5
          },
          {
            "key": "w12-thu-0",
            "title": "1 warm-up problem",
            "description": "1 warm-up problem",
            "track": "DSA",
            "day": "Thu",
            "priority": "medium",
            "status": "todo",
            "order": 6
          },
          {
            "key": "w12-thu-1",
            "title": "Mock system-design round (RADIO, 40 min)",
            "description": "Mock system-design round (RADIO, 40 min)",
            "track": "System Design",
            "day": "Thu",
            "priority": "high",
            "status": "todo",
            "order": 7
          },
          {
            "key": "w12-fri-0",
            "title": "1 warm-up problem",
            "description": "1 warm-up problem",
            "track": "DSA",
            "day": "Fri",
            "priority": "medium",
            "status": "todo",
            "order": 8
          },
          {
            "key": "w12-fri-1",
            "title": "Finalize STAR stories + behavioral",
            "description": "Finalize STAR stories + behavioral",
            "track": "Behavioral",
            "day": "Fri",
            "priority": "low",
            "status": "todo",
            "order": 9
          },
          {
            "key": "w12-sat-0",
            "title": "Second mock machine-coding + system-design",
            "description": "Second mock machine-coding + system-design",
            "track": "Machine Coding",
            "day": "Sat",
            "priority": "high",
            "status": "todo",
            "order": 10
          },
          {
            "key": "w12-sat-1",
            "title": "Full applying push",
            "description": "Full applying push",
            "track": "Main",
            "day": "Sat",
            "priority": "medium",
            "status": "todo",
            "order": 11
          },
          {
            "key": "w12-sun-0",
            "title": "Light review",
            "description": "Light review",
            "track": "Review",
            "day": "Sun",
            "priority": "low",
            "status": "todo",
            "order": 12
          },
          {
            "key": "w12-sun-1",
            "title": "Applying + week-ahead plan",
            "description": "Applying + week-ahead plan",
            "track": "Main",
            "day": "Sun",
            "priority": "medium",
            "status": "todo",
            "order": 13
          }
        ]
      }
    ]
  }
];

export const SEED_VERSION = 1;
